version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: covidliste
      POSTGRES_USER: covidliste
      POSTGRES_DB: covidliste_development
    volumes:
      - "postgres-data:/var/lib/postgresql"
  redis:
    image: "redis:5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
