# This configuration is tailored for use with docker-compose. See DOCKER.md for more information.

default: &default
  adapter: postgresql
  encoding: unicode
  adapter: postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default

test:
  <<: *default
  database: covidliste_test
