# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    # timeout: 15

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      period: ["minute", "hour", "day", "week", "month", "year"]
      vaccine_type: ["astrazeneca", "janssen", "moderna", "pfizer"]
      center_id: "select id, name from vaccination_centers order by name ASC"

      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      # user_id: "/admin/users/{value}"
      center_id: "admin/vaccination_centers/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"
      center_id: "SELECT id, name FROM vaccination_centers WHERE id IN {value}"
      campaign_id: "SELECT id, name FROM campaigns WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
# user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# email to send checks from
from_email: <%= ENV["BLAZER_FROM_ADDRESS"] %>

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "6 hours"
  - "1 hour"
  - "5 minutes"
# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: trend / r

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: trend / prophet

# enable map
# mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>

# enable uploads
# uploads:
#   url: <%= ENV["BLAZER_UPLOADS_URL"] %>
#   schema: uploads
#   data_source: main
