default: &default
  admin_roles:
    super_admin:
      name: "Responsable infrastructure"
    admin:
      name: "Core Team"
      parent_role: super_admin
    supply_admin:
      name: "Responsable supply"
      parent_role: admin
    supply_member:
      name: "Équipe supply"
      parent_role: supply_admin
    ds_admin:
      name: "Responsable data science"
      parent_role: admin
    support_admin:
      name: "Responsable support"
      parent_role: admin
    support_member:
      name: "Équipe support"
      parent_role: support_admin

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
