blazer_checks_5_minute:
  cron: "*/5 * * * *"
  class: "Blazer::RunBlazerChecksJob"
  args: { shedule: "5 minutes" }

blazer_checks_1_hour:
  cron: "0 * * * *"
  class: "Blazer::RunBlazerChecksJob"
  args: { shedule: "1 hour" }

blazer_checks_6_hour:
  cron: "0 */6 * * *"
  class: "Blazer::RunBlazerChecksJob"
  args: { shedule: "6 hours" }

blazer_checks_1_day:
  cron: "0 1 * * *"
  class: "Blazer::RunBlazerChecksJob"
  args: { shedule: "1 day" }

anonynise_confirmed_mathced_users:
  cron: "0 3 * * *"
  class: "AnonymizeConfirmedMatchedUsersJob"
  description: Anonymize all users with confirmed match from 3 days ago and more

run_active_campaigns: # every 1 minute
  cron: "* * * * *"
  class: "RunActiveCampaignsJob"
  description: "Re-evaluate active campaigns"

vmd_parser: # every 2 minute
  cron: "*/2 * * * *"
  class: "VmdParserJob"
  description: "Parse VMD vaccination slots"

follow_up_for_slot_alerts:
  cron: "0 */6 * * *"
  class: "FollowUpSlotAlertsJob"
  description: "Follow up slot alert emails"

send_slots_alerts_for_all:
  cron: "0 7 * * *" # every day at 7am
  class: "SendSlotAlertsJob"
  args: { days: 7, threshold: 100, user_alerting_intensity: 1 }
  description: "Send slots alerts for all users once a day"

send_slots_alerts_for_high:
  cron: "0 11 * * *" # every day at 11aam
  class: "SendSlotAlertsJob"
  args: { days: 2, threshold: 40, user_alerting_intensity: 2 }
  description: "Send slots alerts who want more alerts"


send_slots_alerts_for_power:
  cron: "0 13-21 * * *" # between 1pm to 8pm"
  class: "SendSlotAlertsJob"
  args: { days: 1, threshold: 20, user_alerting_intensity: 3 }
  description: "Send slots alerts who want all alerts"

send_slots_alerts_for_users:
  cron: "0 * * * *" # every hour
  class: "SendSlotAlertsForUsers"
  description: "Send slots alerts using greedy user approach."
